"use client";

import { useEffect, useRef, useState } from "react";

type Props = { projectId: string; initialModel: string; initialEngineerModel?: string; initialMaxSteps: 30 | 60 | 90; repositoryName: string; repositoryUrl: string | null; defaultBranch: string | null };
type Branch = { name: string; protected: boolean; sha: string };
const models = [["gemini-3.1-flash-lite", "Gemini 3.1 Flash-Lite"], ["gemini-3.5-flash", "Gemini 3.5 Flash"]] as const;

export function ProjectConfigurationPanel({ projectId, initialModel, initialEngineerModel = initialModel, initialMaxSteps, repositoryName, repositoryUrl, defaultBranch }: Props) {
  const [model, setModel] = useState(initialModel); const [engineerModel, setEngineerModel] = useState(initialEngineerModel); const [maxSteps, setMaxSteps] = useState<30 | 60 | 90>(initialMaxSteps); const [status, setStatus] = useState("Saved"); const [branches, setBranches] = useState<Branch[] | null>(null); const [branchesError, setBranchesError] = useState<string | null>(null); const initial = useRef(true);
  useEffect(() => { if (initial.current) { initial.current = false; return; } setStatus("Saving…"); const timer = setTimeout(async () => { const response = await fetch(`/api/projects/${projectId}/configuration`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ model, engineerModel, maxSteps }) }); setStatus(response.ok ? "Saved" : "Could not save"); }, 350); return () => clearTimeout(timer); }, [engineerModel, maxSteps, model, projectId]);
  async function inspectBranches() { setBranchesError(null); const response = await fetch(`/api/projects/${projectId}/branches`); const payload = await response.json() as { branches?: Branch[]; error?: string }; if (!response.ok) { setBranchesError(payload.error ?? "Could not load branches."); return; } setBranches(payload.branches ?? []); }
  return <section className="configuration-control-grid"><article className="configuration-control-card"><p className="eyebrow">DEVELOPER</p><div className="configuration-select-row"><label><span>Model</span><select value={model} onChange={(event) => setModel(event.target.value)}>{models.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label><span>Effort</span><select value={maxSteps} onChange={(event) => setMaxSteps(Number(event.target.value) as 30 | 60 | 90)}><option value={30}>Low</option><option value={60}>Medium</option><option value={90}>High</option></select></label></div><small className="configuration-message">{status}</small></article><article className="configuration-control-card"><p className="eyebrow">AI ENGINEER</p><div className="configuration-select-row"><label><span>Model</span><select value={engineerModel} onChange={(event) => setEngineerModel(event.target.value)}>{models.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label></div><small className="configuration-message">{status === "Saving…" ? "Saving…" : "Used for planning and review configuration."}</small></article><article className="configuration-control-card"><p className="eyebrow">GIT &amp; REPOSITORY</p><h2>{repositoryName}</h2><p>Default branch: <code>{defaultBranch ?? "Not connected"}</code></p>{repositoryUrl ? <a className="text-link" href={repositoryUrl} target="_blank" rel="noreferrer">Open repository ↗</a> : null}<button className="button secondary" type="button" disabled={!defaultBranch} onClick={inspectBranches}>Inspect branches</button>{branchesError ? <small className="configuration-message error">{branchesError}</small> : null}{branches ? <ul className="branch-list">{branches.map((branch) => <li key={branch.name}><code>{branch.name}</code>{branch.name === defaultBranch ? <b>default</b> : null}{branch.protected ? <b>protected</b> : null}<small>{branch.sha.slice(0, 8)}</small></li>)}</ul> : <small>Branch inspection is read-only. Task branches remain created and merged through Dashboard.</small>}</article></section>;
}
